=== BelimFaux/Raytracer/scenes/scene.dtd
<!ELEMENT scene (background_color, super_sampling?, animated?, camera, lights, surfaces)>
<!ELEMENT background_color EMPTY>
<!ELEMENT super_sampling EMPTY>
<!ELEMENT animated EMPTY>

<!ELEMENT camera (position, lookat, up, horizontal_fov, depth_of_field?, resolution, max_bounces)>
<!ELEMENT position EMPTY>
<!ELEMENT lookat EMPTY>
<!ELEMENT up EMPTY>
<!ELEMENT horizontal_fov EMPTY>
<!ELEMENT depth_of_field EMPTY>
<!ELEMENT resolution EMPTY>
<!ELEMENT max_bounces EMPTY>

<!ELEMENT lights ((ambient_light | point_light | parallel_light | spot_light)*)>
<!ELEMENT ambient_light (color)>
<!ELEMENT point_light (color, position)>
<!ELEMENT parallel_light (color, direction)>
<!ELEMENT spot_light (color, position, direction, falloff)>
<!ELEMENT color EMPTY>
<!ELEMENT direction EMPTY>
<!ELEMENT falloff EMPTY>

<!ELEMENT surfaces ((sphere | mesh | julia_set)*)>
<!ELEMENT sphere (position, endposition?, (material_solid | material_textured), transform?)>
<!ELEMENT endposition EMPTY>
<!ELEMENT mesh ((material_solid | material_textured), transform?)>
<!ELEMENT julia_set (position, constant, endconstant?, material_solid, transform?)>
<!ELEMENT constant EMPTY>
<!ELEMENT endconstant EMPTY>

<!ELEMENT material_solid (color, (phong | cook_torrance), reflectance, transmittance, refraction)>
<!ELEMENT material_textured (texture, (phong | cook_torrance), reflectance, transmittance, refraction)>
<!ELEMENT phong EMPTY>
<!ELEMENT cook_torrance EMPTY>
<!ELEMENT reflectance EMPTY>
<!ELEMENT transmittance EMPTY>
<!ELEMENT refraction EMPTY>
<!ELEMENT texture EMPTY>

<!ELEMENT transform ((translate | scale | rotateX | rotateY | rotateZ)*)>
<!ELEMENT translate EMPTY>
<!ELEMENT scale EMPTY>
<!ELEMENT rotateX EMPTY>
<!ELEMENT rotateY EMPTY>
<!ELEMENT rotateZ EMPTY>



<!ATTLIST scene output_file CDATA #REQUIRED>

<!ATTLIST background_color
	r NMTOKEN #REQUIRED
	g NMTOKEN #REQUIRED
	b NMTOKEN #REQUIRED>

<!ATTLIST animated
	frames NMTOKEN #REQUIRED
	fps NMTOKEN #REQUIRED>

<!ATTLIST super_sampling
	samples NMTOKEN #REQUIRED>

<!ATTLIST position
	x NMTOKEN #REQUIRED
	y NMTOKEN #REQUIRED
	z NMTOKEN #REQUIRED>

<!ATTLIST lookat
	x NMTOKEN #REQUIRED
	y NMTOKEN #REQUIRED
	z NMTOKEN #REQUIRED>	

<!ATTLIST up
	x NMTOKEN #REQUIRED
	y NMTOKEN #REQUIRED
	z NMTOKEN #REQUIRED>

<!ATTLIST horizontal_fov
	angle NMTOKEN #REQUIRED>

<!ATTLIST depth_of_field
	focal_length NMTOKEN #REQUIRED
	aperture NMTOKEN #REQUIRED>

<!ATTLIST resolution
	horizontal NMTOKEN #REQUIRED
	vertical NMTOKEN #REQUIRED>

<!ATTLIST max_bounces
	n NMTOKEN #REQUIRED>

<!ATTLIST color
	r NMTOKEN #REQUIRED
	g NMTOKEN #REQUIRED
	b NMTOKEN #REQUIRED>

<!ATTLIST direction
	x NMTOKEN #REQUIRED
	y NMTOKEN #REQUIRED
	z NMTOKEN #REQUIRED>

<!ATTLIST falloff
	alpha1 NMTOKEN #REQUIRED
	alpha2 NMTOKEN #REQUIRED>

<!ATTLIST sphere
	radius NMTOKEN #REQUIRED
  endradius NMTOKEN #IMPLIED>

<!ATTLIST endposition
	x NMTOKEN #REQUIRED
	y NMTOKEN #REQUIRED
	z NMTOKEN #REQUIRED>

<!ATTLIST mesh
	name CDATA #REQUIRED>

<!ATTLIST julia_set
	max_iteration NMTOKEN #REQUIRED
  epsilon NMTOKEN #REQUIRED>

<!ATTLIST constant
	x NMTOKEN #REQUIRED
	y NMTOKEN #REQUIRED
	z NMTOKEN #REQUIRED
	w NMTOKEN #REQUIRED>

<!ATTLIST endconstant
	x NMTOKEN #REQUIRED
	y NMTOKEN #REQUIRED
	z NMTOKEN #REQUIRED
	w NMTOKEN #REQUIRED>

<!ATTLIST phong
	ka NMTOKEN #REQUIRED
	kd NMTOKEN #REQUIRED
	ks NMTOKEN #REQUIRED
	exponent NMTOKEN #REQUIRED>

<!ATTLIST cook_torrance
	ka NMTOKEN #REQUIRED
	ks NMTOKEN #REQUIRED
	roughness NMTOKEN #REQUIRED>

<!ATTLIST reflectance
	r NMTOKEN #REQUIRED>

<!ATTLIST transmittance
	t NMTOKEN #REQUIRED>

<!ATTLIST refraction
	iof NMTOKEN #REQUIRED>

<!ATTLIST texture
	name CDATA #REQUIRED>

<!ATTLIST translate
	x NMTOKEN #REQUIRED
	y NMTOKEN #REQUIRED
	z NMTOKEN #REQUIRED>

<!ATTLIST scale
	x NMTOKEN #REQUIRED
	y NMTOKEN #REQUIRED
	z NMTOKEN #REQUIRED>

<!ATTLIST rotateX
	theta NMTOKEN #REQUIRED>

<!ATTLIST rotateY
	theta NMTOKEN #REQUIRED>

<!ATTLIST rotateZ
	theta NMTOKEN #REQUIRED>

=== BelimFaux/Raytracer/scenes/julia_set.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE scene SYSTEM "scene.dtd">

<scene output_file="julia_set.png">
    <background_color r="0.0" g="0.0" b="0.0"/>
    <super_sampling samples="16"/>
    <camera>
        <position x="0.0" y="0.0" z="1.0"/>
        <lookat x="0.0" y="0.0" z="-2.5"/>
        <up x="0.0" y="1.0" z="0.0"/>
        <horizontal_fov angle="45"/>
        <resolution horizontal="1024" vertical="1024"/>
        <max_bounces n="8"/>
    </camera>
    <lights>
        <ambient_light>
            <color r="1.0" g="1.0" b="1.0"/>
        </ambient_light>
        <point_light>
            <color r="0.7" g="0.7" b="0.7"/>
            <position x="1.5" y="3.0" z="-2.5"/>
        </point_light>
        <point_light>
            <color r="0.7" g="0.7" b="0.7"/>
            <position x="-1.5" y="3.0" z="-2.5"/>
        </point_light>
    </lights>
    <surfaces>
        <julia_set max_iteration="8" epsilon="0.006">
            <position x="0.0" y="0.0" z="-2.0"/>
            <constant x="-0.5" y="-0.3" z="0.6" w="0.0"/>
            <material_solid>
                <color r="0.9" g="0.3" b="0.4"/>
                <cook_torrance ka="0.2" ks="0.4" roughness="0.3"/>
                <reflectance r="0.5"/>
                <transmittance t="0.0"/>
                <refraction iof="2.0"/>
            </material_solid>
            <transform>
                <scale x="1.5" y="1.5" z="1.5"/>
            </transform>
        </julia_set>
        <mesh name="open_room.obj">
            <material_textured>
                <texture name="rainbow.png"/>
                <phong ka="0.3" kd="0.9" ks="1.0" exponent="20"/>
                <reflectance r="0.0"/>
                <transmittance t="0.0"/>
                <refraction iof="0.0"/>
            </material_textured>
        </mesh>
    </surfaces>
</scene>

=== BelimFaux/Raytracer/scenes/test.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE scene SYSTEM "scene.dtd">

<scene output_file="test.png">
    <background_color r="0.0" g="0.0" b="0.0"/>
    <super_sampling samples="4"/>
    <camera>
        <position x="0.0" y="0.0" z="1.0"/>
        <lookat x="0.0" y="0.0" z="-2.5"/>
        <up x="0.0" y="1.0" z="0.0"/>
        <horizontal_fov angle="45"/>
        <depth_of_field focal_length="5.5" aperture="0.1"/>
        <resolution horizontal="1024" vertical="1024"/>
        <max_bounces n="4"/>
    </camera>
    <lights>
        <ambient_light>
            <color r="1.0" g="1.0" b="1.0"/>
        </ambient_light>
        <point_light>
            <color r="0.7" g="0.7" b="0.7"/>
            <position x="1.5" y="3.0" z="-2.5"/>
        </point_light>
    </lights>
    <surfaces>
        <mesh name="queen.obj">
            <material_solid>
                <color r="1.0" g="1.0" b="1.0"/>
                <cook_torrance ka="0.3" ks="0.4" roughness="0.25"/>
                <reflectance r="0.2"/>
                <transmittance t="0.0"/>
                <refraction iof="2.0"/>
            </material_solid>
            <transform>
                <translate x="1.0" y="-2.15" z="-4"/>
            </transform>
        </mesh>
        <mesh name="base.obj">
            <material_textured>
                <texture name="mramor6x6.png"/>
                <phong ka="0.3" kd="0.9" ks="0.0" exponent="20"/>
                <reflectance r="0.4"/>
                <transmittance t="0.0"/>
                <refraction iof="0.0"/>
            </material_textured>
            <transform>
                <translate x="0.0" y="-2.5" z="-5"/>
            </transform>
        </mesh>
    </surfaces>
</scene>

=== BelimFaux/Raytracer/scenes/cook-torrance.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE scene SYSTEM "scene.dtd">

<scene output_file="cook_torrance.png">
    <background_color r="0.0" g="0.0" b="0.0"/>
    <camera>
        <position x="1.0" y="4.0" z="-1.0"/>
        <lookat x="0.0" y="0.0" z="-4.0"/>
        <up x="0.0" y="1.0" z="0.0"/>
        <horizontal_fov angle="45"/>
        <resolution horizontal="1024" vertical="1024"/>
        <max_bounces n="8"/>
    </camera>
    <lights>
        <ambient_light>
            <color r="1.0" g="1.0" b="1.0"/>
        </ambient_light>
        <point_light>
            <color r="0.7" g="0.7" b="0.7"/>
            <position x="2.0" y="3.0" z="-2.5"/>
        </point_light>
        <point_light>
            <color r="0.7" g="0.7" b="0.7"/>
            <position x="-2.0" y="3.0" z="-2.5"/>
        </point_light>
    </lights>
    <surfaces>
        <sphere radius="1.0">
            <position x="1.5" y="0.0" z="-2.4"/>
            <material_textured>
                <texture name="mramor6x6.png"/>
                <cook_torrance ka="0.3" ks="0.6" roughness="0.25"/>
                <reflectance r="0.0"/>
                <transmittance t="0.0"/>
                <refraction iof="0.0"/>
            </material_textured>
        </sphere>
        <sphere radius="1.0">
            <position x="-1.0" y="0.5" z="-3.4"/>
            <material_solid>
                <color r="0.95" g="0.63" b="0.01"/>
                <cook_torrance ka="0.3" ks="0.7" roughness="0.4"/>
                <reflectance r="0.0"/>
                <transmittance t="0.0"/>
                <refraction iof="0.0"/>
            </material_solid>
        </sphere>
        <mesh name="open_room.obj">
            <material_textured>
                <texture name="MarbleBeige.png"/>
                <cook_torrance ka="0.3" ks="0.3" roughness="0.6"/>
                <reflectance r="0.0"/>
                <transmittance t="0.0"/>
                <refraction iof="0.0"/>
            </material_textured>
        </mesh>
    </surfaces>
</scene>
